require "user.plugins.configs.treesitter"
require "user.plugins.configs.copilot"
-- require "user.plugins.configs.devicons"
require "user.plugins.configs.bufferline"
require "user.plugins.configs.gitsigns"
require "user.plugins.configs.lualine"
