require "user.plugins.keymaps.hop"
require "user.plugins.keymaps.nerdtree"
require "user.plugins.keymaps.telescope"
require "user.plugins.keymaps.undotree"
require "user.plugins.keymaps.fugitive"
require "user.plugins.keymaps.symbols-outline"
