require "user.options"
require "user.keymaps.base"
require "user.keymaps.plugins.hop"
require "user.keymaps.plugins.coc"
require "user.keymaps.plugins.nerdtree"
require "user.plugins"
require "user.completion"
